### ISSUE TITLE
Version 1.3 is not working with Camunda 7.11.0-SNAPSHOT

### ISSUE THREAD

**Issue by pschalk** [camunda/camunda-bpm-custom-batch#25]
Because Camunda uses with 7.11 now google.gson instead of the own json implementation:

CustomBatchConfigurationJsonConverter.java:[37,10] cannot find symbol
  symbol:   class JSONObject

**Comment by tomconn** [comment]
Any rough estimate of when the 1.4 will be released supporting Camunda 7.11?

I'm planning on upgrading, to Camunda 7.11, so I'd like to align with the batch dependency.

**Comment by pschalk** [comment]
Hi tom,

I'll do it as soon as possible. ;) 

Best regards,
Patrick

**Comment by pschalk** [comment]
Will be fixed with 1.4.0 release, see #27
